validates:
  maximum_name: 50
  maximum_email: 200
  minimum_pass: 6
  maximum_content: 140
gravatar:
  size: 80
  size_small: 50
  size_xl: 30
remember_checked: 1
iamge_extensions: "image/jpeg,image/gif,image/png"
image_width: 300
